<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <AssemblyName>XboxControllerPatch</AssemblyName>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net46" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepInEx.Preloader">
      <HintPath>lib/BepInEx.Preloader.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>lib/BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>lib/Mono.Cecil.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
